### ISSUE TITLE
 The OS doesn't support SO_REUSEPORT: cannot enable SO_REUSEPORT: protocol not available

### ISSUE THREAD

**Issue by jason000zhang** [medcl/infini-gateway#19]
如题，应该是在centos6上会报这个错误

**Comment by medcl** [comment]
恩，这个是端口重用的，多进程可以共享端口，你测试的是 centos6 是 64 位还是 32 位啊，我也试试看。

你可以暂时把配置里面的这段：
```
entry:
  - name: es_gateway #your gateway endpoint
    enabled: true
#    router: default #configure your gateway's routing flow
    router: not_found #configure your gateway's routing flow
    network:
      binding: 0.0.0.0:8000
#      skip_occupied_port: false
      reuse_port: true #you can start multi gateway instance, they share same port, to full utilize system's resources
```

把 `reuse_port: true ` 改成 `reuse_port: false `，看看好不好用？
