### ISSUE TITLE
請問有支援同時寫入多個 Elasticsearch Cluster 的 flow 嗎？

### ISSUE THREAD

**Issue by hashman** [medcl/infini-gateway#27]
感謝大神的貢獻拜讀了 <(_ _)> 看了一下文章，有支援不同環境的 Elasticsearch config 設定，但好像沒有看到可以同時將資料寫入不同 Elasticsearch Cluster 的功能，感謝說明

**Comment by medcl** [comment]
@hashman 使用 clone filter 即可，配置如下：

```
flow:
  - name: double_write
    filter:
      - name: trafic_clone
        type: clone
        parameters:
          flows:
            - write_to_es_a
            - write_to_es_b
  - name: write_to_es_a
    filter:
      - name: elasticsearch
        parameters:
          elasticsearch: es1
  - name: write_to_es_b
    filter:
      - name: elasticsearch
        parameters:
          elasticsearch: es2

elasticsearch:
- name: es1
  enabled: true
  version: 7.6.0
  endpoint: http://127.0.0.1:8081 
- name: es2
  enabled: true
  version: 5.6.0
  endpoint: http://127.0.0.1:8082  

```

在 router 里面使用 `double_write` 就行了。
有问题可以再留言。
