### ISSUE TITLE
响应返回

### ISSUE THREAD

**Issue by MrLiukang** [medcl/infini-gateway#37]
``` 
flow:
  - name: double_write
    filter:
      - name: clone
        parameters:
          flows:
            - write_to_region_a
            - write_to_region_b #last one's response will be output to client
  - name: write_to_region_a
    filter:
      - name: elasticsearch
        parameters:
          elasticsearch: es1
  - name: write_to_region_b
    filter:
      - name: elasticsearch
        parameters:
          elasticsearch: es2
```
这个有办法可以返回两个的集群的信息吗
