### ISSUE TITLE
索引文档差异比对功能支持字段配置和排除吗？

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [medcl/infini-gateway#44]
@medcl 由于目前这部分特性在官方文档中并没有具体说明，所以想问一下大大，这个支持字段黑白名单设置吗？dump后只对特定的字段算hash，后续diff操作。看官方文档的示例，貌似没找到类似的配置
```yaml
pipelines_v2:
  - name: index_diff_service
    processors:
    - dag:
        parallel:
          - dump_hash: #dump es1's doc
              indices: "medcl-test"
              scroll_time: "10m"
              elasticsearch: "source"
              output_queue: "source_docs"
              batch_size: 10000
              slice_size: 5
          - dump_hash: #dump es2's doc
              indices: "medcl-test"
              scroll_time: "10m"
              batch_size: 10000
              slice_size: 5
              elasticsearch: "target"
              output_queue: "target_docs"
        end:
          - index_diff:
              diff_queue: "diff_result"
              buffer_size: 1
              text_report: true #如果要存 es，这个开关关闭，开启 pipeline 的 diff_result_ingest 任务
              source_queue: 'source_docs'
              target_queue: 'target_docs'
```

本来想自己下载代码，看看源码确认下。但不知道该如何下手，idea全局搜dump hash类似的关键字，也没找到入手点。
请问目前源码上传的是最新的吗？本人刚接触go语言没多久，对于源码模块结构说明及依赖说明和编译打包，希望能有点文档帮助信息。
